server:
  port: 9091

spring:
  application:
    name: team-service
  datasource:
    url: jdbc:postgresql://localhost:5432/team_service
    username: postgres
    password: 4002
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
