server:
  port: 9090

spring:
  application:
    name: driver-service
  datasource:
    url: jdbc:postgresql://localhost:5432/driver_service
    username: postgres
    password: 4002
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
